itslabelme/itslabel.me

app/controllers/admin/profile_controller.rb
app/views/admin/admin_users/edit.js.erb
app/views/admin/admin_users/form/_form.html.erb
app/views/admin/label_templates/form/_form.html.erb
app/views/admin/label_templates/form/_form.js.erb
app/views/admin/profile/form/_form.html.erb
app/views/admin/translations/edit.js.erb
app/views/admin/translations/form/_form.html.erb
app/views/admin/translations/form/_form.js.erb
app/views/admin/translations/index.html.erb
app/views/admin/translations/new.js.erb

Cancel Button Fix

---

app/controllers/user/client_profile_controller.rb
app/views/layouts/user/_left_sidebar.html.erb
app/views/user/client_profile/edit.html.erb
app/views/user/client_profile/form/_change_password.html.erb
app/views/user/client_profile/form/_update_profile.html.erb
app/views/user/client_profile/update_password.js.erb
config/routes.rb
nbproject/project.xml

User Profile password

---

.gitignore
app/models/client_user.rb
app/views/admin/client_users/index/_table.html.erb
db/seeds.rb
nbproject/project.xml

contry fix

---

app/views/user/template_documents/print.html.erb
nbproject/project.xml

Hide the Download as PDF button from the preview

remove download pdf

---

app/views/user/free_form_widget/index/_widget.js.erb

Fix Delete

---

app/controllers/admin/label_templates_controller.rb
app/views/admin/label_templates/form/_form.html.erb
app/views/user/template_documents/select_template/_index.html.erb
db/migrate/20200426050036_create_additional_field_to_label_template.rb

Added Status Column in db for label template and drop down in add and edit form

ADD ACTIVE AND INACTIVE REMOVED

---

app/views/user/free_form_widget/index.html.erb
app/views/user/home/widgets/_new_document.html.erb
app/views/user/template_documents/select_template.html.erb
app/views/user/template_documents/show/_details.html.erb

Tools edited on ITS-client module.

tools edited

---

app/views/user/template_documents/show/_details.html.erb

Please check the dropdown modified on the template transalation.

dropdown modified

---

app/views/user/document_folder/form/_form.html.erb

Please check the headings changed on folder edit section

edit label added

---

app/views/user/document_folder/form/_form.html.erb

Validation added on the folder creation

validation added

---

app/views/user/documents/index/_folders.html.erb

Remove folder icon removed both parent and sub folders

Remove folder fixed

---

app/views/user/documents/index/_folders.html.erb
app/views/user/documents/index/_nested_folders.html.erb

Fixed dragging of documents to sub folders

Dragging fixed

---

app/views/user/table_documents/common/_form.html.erb
app/views/user/template_documents/select_template.html.erb

Casing fixed in free form, Template based and table based  headers.

It 13- Casing Fixed

---

app/views/admin/upload_translations/form/_form.html.erb
app/views/admin/upload_translations/index/_index.html.erb

Disabled multiple uploads in translations.

Its ui-modification

---

app/controllers/admin/translation_uploads_history_controller.rb
app/views/admin/translation_uploads_history/index/_header.html.erb
app/views/admin/translation_uploads_history/index/_table.html.erb
app/views/admin/translation_uploads_history/show/_header.html.erb

Ui fixed for Database upload history

It 74 -Ui fixed

---

app/views/admin/translations/index/_controls.html.erb

Searched item displayed in translation database.

searched item displayed

---

app/controllers/concerns/table_settings/translation_requests_ts.rb
app/views/admin/translation_requests/index/_table.html.erb
app/views/admin/translation_requests/index/_table.js.erb
app/views/user/table_documents/common/_form.html.erb

modified user side table documents ui with csv import button

It 91- CSV import fixed

---

app/views/user/template_documents/show/_details.html.erb

Print removed and Preview hide in template documents

print and preview removed

---

app/views/admin/client_feedbacks/index/_table.js.erb
app/views/admin/translation_requests/index/_table.js.erb

Removed the gap between table header and table data in clients feedback and translation request page

ILM-67 -Fixed

---

app/views/admin/client_feedbacks/index/_table.js.erb
app/views/admin/translation_requests/index/_table.js.erb
app/views/devise/sessions/new.html.erb
app/views/user/template_documents/show/_template.js.erb

Hided image tag and clipboard of template section

ILM 125 - hided image tag

---

app/controllers/admin/admin_users_controller.rb
app/controllers/admin/client_feedbacks_controller.rb
app/controllers/admin/client_users_controller.rb
app/controllers/admin/translation_query_histories_controller.rb
app/controllers/user/free_form_widget_controller.rb
app/controllers/user/table_documents_controller.rb
app/jobs/log_translation_query_job.rb
app/models/client_feedback.rb
app/models/concerns/itslabel/log_methods.rb
app/views/admin/admin_users/index/_table.js.erb
app/views/admin/client_feedbacks/index/_table.js.erb
app/views/admin/client_users/index/_table.js.erb
app/views/admin/translation_query_histories/index/_table.js.erb
app/views/admin/translation_requests/index/_table.js.erb
app/views/user/client_feedbacks/form/_form.html.erb
app/views/user/free_form_widget/create_translation_request.js.erb

Modified data tables

---

app/views/devise/mailer/reset_password_instructions.html.erb
app/views/user_mailer_notification/send_welcome_email.html.erb

address modified

---

app/controllers/admin/translation_uploads_history_controller.rb
app/views/admin/translation_query_histories/index/_controls.html.erb
app/views/admin/translation_uploads_history/show/_show.html.erb
app/views/admin/translations/index/_controls.html.erb

modified Admin side history detail page

modified history detail page

---

app/controllers/user/template_documents_controller.rb
app/views/user/template_documents/show/_details.html.erb

Saving an edited template into a specific folder

template fixed

---

app/controllers/user/table_documents_controller.rb
app/models/table_document_item.rb
app/views/user/table_documents/common/_form.html.erb
app/views/user/table_documents/common/_table.js.erb
app/views/user/table_documents/csv_upload/_form.html.erb

csv import issue fixed in table document.

CSV import fixed

---

app/views/user_mailer_notification/send_welcome_email.html.erb

Modified the welcome mail template in client user signup

ILM-189 - Welcome mail modified

---

app/assets/stylesheets/custom.css
app/controllers/application_controller.rb
app/models/client_user.rb
app/views/admin/client_users/index/_table.html.erb
app/views/devise/registrations/_registration.js.erb
app/views/devise/registrations/new.html.erb
app/views/devise/registrations/policies.html.erb
config/routes.rb
db/migrate/20210621105829_add_t_c_accepted_to_client_users.rb
db/migrate/20210622091408_data_correction_june_22.rb
db/schema.rb

Added terms and conditions in ITS signup.

T and C added

---

app/views/user/table_documents/common/_form.html.erb
app/views/user/table_documents/csv_upload/_form.html.erb

Text changed in table mode translation at client side

ILM-187 - text changed

---

app/controllers/application_controller.rb

Fixed recaptcha issue in admin side

fixed captcha

---

app/controllers/user/omniauth_callbacks_controller.rb
app/models/client_user.rb

Google signup Fixed by modified validations

Google signup fixed

---

app/views/user/template_documents/show/_template.js.erb

Fixed responsive issue in tinyMCE editor

fixed menubar in mobile view

---

app/controllers/application_controller.rb
app/mailers/user_mailer_notification.rb
app/models/client_user.rb
app/views/admin/home/index.html.erb
app/views/devise/registrations/new.html.erb
db/migrate/20210720053701_add_flag_to_client_users.rb
db/schema.rb
db/seeds.rb

Fixed Welcome mail issue on seed data

Flag added to fix welcome mail on seeding
